name: Generate Manual

on:
  schedule:
    - cron: '0 2 * * 6'

jobs:
  generate:
    runs-on: ubuntu-20.04
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/denoland/deno
          TAG="$(python3 tag.py)"
          echo "::set-env name=DENOTAG::$TAG"
          cd deno && git checkout tags/"$TAG" && cd ..
          echo "::set-env name=FILELIST::$(python3 files.py)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: --metadata-file=conf.yml --listings --pdf-engine=xelatex --resource-path=deno/docs/images -o manual.pdf ${{ env.FILELIST }}
      - run: |
          mkdir -p build
          mv manual.pdf build/deno-manual-$DENOTAG.pdf
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add build
          git commit -m "$DENOTAG - update manual"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
